datasektionen/styrdokument

reglemente.tex
Funktionärsposterna SSO, Chefredaqtören och Kommunikatör (fd informationsansvarig och systemansvarig) samt d-Smf ändrades.
=> Ändringar gjorda enligt beslut tagna på Revisions-SM 3 mars 2015.

ekonomiskt_styrdokument/body.md
Uppdatering av det ekonomiska styrdokumentet enligt proposition lagd till Val-SM 2016.
Ska endast mergeas om propositionen bifalles i sin helhet. Annars ska yrkanden in först.
=> Val-SM 2016 - Prop. ang. Uppdatering av Ekonomiskt Styrdok.

reglemente/body.md
dbuggen stavas uteslutande exakt `dbuggen`
=> Redaktionell ändring

reglemente/body.md
Budget SM, Motion angående nämnd till ISC.
Beslutsuppföljning av att lägga in Internationella Nämnden i reglementet enligt ISC motion.
Protokollet från Budget-SM är inte uppe, men motionen finns i handlingarna [här](https://drive.google.com/file/d/0B_TphSD6GcSRb1VvTjlyNDRyM1k/view)
@avelinpv
=> Budget-SM 2017: Motion angående nämnd till ISC

reglemente/body.md
Reglementesändringar till följd av "Motion angående D-Dagens budget".
att i reglementets §3.7.2 (Nämnder → Näringslivsgruppen → Organisation) lägga till följande: “Näringslivsgruppen utom D-Dagen och D-Dagen budgeteras separat. Näringslivsansvarig och D-Dagenansvarig har båda attesträtt för verksamheten i hela nämnden
Näringslivsgruppen.”
=> Motion angående D-Dagens budget

reglemente/body.md
Omformulerade för att det skulle hållas konsekvent samt flyttade punkten till det nya slutet av listan.
=> Infogat 2 punkter under §4.1.3

reglemente/body.md
Tog bort stycket om att dela ut Crashmedaljer enligt beslut från Revisions-SM 2021.
=> Revisions-SM, 6.5 Vaskandet av Crashmedaljer

reglemente/body.md
Ändrade till meningen:
`Valberedningen har till uppgift att opartiskt administrera och bereda de val som genomförs vid sektionen samt göra bedömningar av kandidaters lämplighet.`
=> Motion angående valberedningens ändamål

reglemente/body.md
Ändrade reglementet enligt Proposition 4: "Proposition angående flytta JML-ansvar inom styrelsen" från val-SM 2021-05-18.
Bifallet beslut nedan:
Förslag till beslut
att1
i reglementets §3.4.2 Organisation ändra från 
”Nämnden leds av Jämlikhetsnämndens ordförande. Styrelseledamoten för studiesocialafrågor skall också ingå i nämnden tillsammans med övriga intresserade sektionsmed-lemmar.”
till
”Nämnden leds av Jämlikhetsnämndens ordförande. Styrelseledamoten för utbildnings-frågor skall också ingå i nämnden tillsammans med övriga intresserade sektionsmed-lemmar.”
att2
i reglementets §4.1.7 Ledamot för studiesociala frågor ta bort ”från styrelsen arbetamed frågor som berör jämlikhet, mångfald och likabehandling på sektionen.”
att3
i reglementets §4.1.8 Ledamot för utbildningsfrågor lägga …
=> beslutsuppf prop 4 val-sm 210518

reglemente/body.md
Ändrat reglementet enl propostion ang D-dagenexit. Pga miss av tidigare beslutsuppföljning behövde rubriken för D-dagen under rubrik 3 ändras från proppens förslag 3.21 till 3.22 då 3.21 redan var upptaget av Scala.
=> Beslutsuppf budget-SM 211109 D-dagenexit

dfunkpolicy/body.md
Ändrar så att dfunk endast behöver gå på en dfunkutbildning och inte en per mandatperiod. 
Drek kan säga att de måste gå ändå.
=> 22S02-06 Beslutsuppf. prop 5 dFunkpol val-sm 2022

reglemente/body.md
Attempt to fix list in D-dagens reglemente.
Not tested locally since the `bawang-styrdokument -> taitan -> styrdokument` chain is a bit annoying to setup locally, but it is the same format as other lists now, so it should work.
=> Redaktionell ändring - fixa lista i D-Dagens reglemente

jamlikhetspolicy/body.md, klimatpolicy/body.md
The links in jämlikhetspolicyn and miljöpolicyn were either not working or linking to old documents.
I think it is best to link to the drive folders rather than the PDF documents since they will (hopefully) also contain all updated policies in the future as well. 
should be a redaktionell ändring
=> Update links in policy documents

stadgar/body.md
Missad beslutsuppföljning från budget-sm 2017. Om att D-rek ej behöver besvara motioner som dras tillbaka innan SM. Proposition angående Städ i formalian.
Denna del av beslutet har inte påverkats av något av besluten tagna på SM 2018-2022.
=> 17S03-01 Stageändring budget-sm 2017 

stadgar/body.md
Beslutsuppföljning som hade missats från Glögg-SM 2017 om att motion kan begära misstroendeförklaring mot förtroendevald. Obs att denna mening behöver vara efter stadgeändringen i 17S03-01. 
Det här beslutet har inte påverkats av beslut tagna på SM mellan 2018-2022.
=> 17S04-02 Stadgeändring Glögg-SM 2017

stadgar/body.md
På Val-SM 2018 så beslutades det att inte ha med den sista meningen i stycket. Dvs. "Den del av projektets budget som tillhör sektionen förfogas över enligt sektionens ekonomiska styrdokument.". Men när beslutsuppföljningen gjordes för punkten så verkar det som att meningen råkade hamna med. I motionen "Motion angående Delade Projekt i stadgarna"
Denna del av stadgarna har inte ändrats i något av de övriga SM:erna 2018-2022.
=> 18S02-02 Korrigering av beslutuppf. Val-SM 2018

reglemente/body.md
Under beslutsuppföljningen efter glögg-SM användes inte en konsekvent policy för hur konsekvensnumreringen skulle utföras. 
Mer specifikt så väntade #229 med att göra det med tanken att den skulle göras i #240 , medans exempelvis #236 gjorde det i förväg. Slutresultatet blev att vi missade några, så den här PRen fixar det.
Noterade det här när jag kollade igenom reglementet för en sak och kände lite ansvar iom att jag reviewade alla dessa, så hoppas det är ok att jag PRar trots att jag inte är d-rektorat längre.
=> Fixa missad konsekvensnumrering från Glögg-SM

reglemente/body.md
Tar bort Idrottsnämndens verksamhet från reglementet. Då detta missades i PR som verkställde resterande del av proppen.
=> 23S04-1 Tar bort missad verksamhet i reglementet

pm/pm_verksamhet/body.md
In the rendered HTML, they were part of the preceding list, which made them indented. Not sure if it's a skill issue of the markdown parser we're using or however wrote this PM in markdown, but does not matter from now on.
=> Put newlines before headings

reglemente/body_sv.md
Reglementesändringar, bifall av motionssvaret.
Ändringar:
I reglementet:
-  §3.16.1 stryka “, på engelska the International Group,” 
-  §5.2.17 stryka “International student coordinator, förkortat ISC, är det engelska namnet.”
=> 24S04-05 - Internationella nämndens identitet

reglemente/body_sv.md
Jag vet att Kommunikationsgruppen är cool men vi behöver nog inte så stora titlar för att visa det.
=> Korrigera Kommunikationsgruppens titelstorlek

pm/pm_dfunk/body_sv.md, pm/pm_ekonomi/body_sv.md, policies/uppforandepolicy/body_sv.md, reglemente/body_sv.md, stadgar/body_sv.md
Löser problem med konsekvensnumrering och pekarreferenser i #339. Jag anser att det är en del av konsekvensnumreringen.
De tre commit:sen 41df2cd0933d4612470df2073a631d72e82e919a, 8fe407f6d19fd6ba850b9946bf5d459298eb872d samt dfb8c81c9b3620db04d1ea60774dc5172740af4d är mest najs redaktionella tolkningar att ha och ger pekare i alla PMs samt rätt tecken § istället för fel $.
Kom gärna med tycke om några ändringar är för grova.
=> Konsekvensnumrera pekare

pm/pm_informationshantering/body_sv.md
Redaktionella ändringar som borde tagits i #335 .
fca1d673fa4d1b7415e4c94679a51a2137d55ff2 består av ren stavningskorrigering och tillägg av mellanrum.
692696594646273d0058fdaab0dba664aef86127 lägger till pronomen för att meningen ska vara grammatiskt korrekt.
=> 24D12-02 Redaktionella ändringar
