- alkoholpolicy.tex
- dfunkpolicy.tex
- ekonomiskt_styrdokument.tex
- informationsspridningsguidelines.tex
- jamlikhetspolicy.tex
- reglemente.tex
- rekryteringspolicy.tex
Ändringar i reglemente, ek styrdok och alkoholpolicyn. Vissa redaktionella ändringar.
> Tillagda policies och ändringar enligt beslut på Val-SM 2015

- reglemente.tex
Ändringar reglementet gjorda enligt "Proposition angående införande av Kassörsorder"
Propositionen finns på sidan 85 i protokollet nedan:
http://datasektionen.se/sektionen/formalia/protokoll/sm_protokoll_20151020.pdf
> Budget-SM 2015: Proposition angående införande av Kassörsorder

- reglemente.tex
- stadgar.tex
Ändringar gjorda i stadgarna enligt andra läsningen av följande motioner och propositioner:
- Motion angående Valberedningens utökande samt förlängning av nomineringsstopp vid behov
- Proposition angående projektens bokföringsplikt
- Verksamhetsplaner för återkommande projekt
Ändringar gjorda i reglementet enligt följande motioner och propositioner:
- Motion angående Justering av förbuden i META
- Motion angående ändring av gamla saker om Mottagningen i reglementet
- Proposition angående D-dagenansvarig
Protokoll finns här:
datasektionen.se/sektionen/formalia/protokoll/sm_protokoll_20151020.pdf
> Beslutsuppföljning från Budget-SM 2015

- reglemente.tex
- stadgar.tex
Beslutsuppföljning från Budget-SM 2015
Stadgarändringar:
* Proposition angående mindre summor
Reglementesändringar:
* Proposition angående Chefredaqtörens mandatperiod
> Budget-SM 2015: Beslutsuppföljning

- alkoholpolicy.tex
- reglemente.tex
- stadgar.tex
Uppföljning enligt protokoll: https://datasektionen.se/sektionen/formalia/protokoll/gloggsm15_protokoll_20151207.compressed.pdf
> Glögg-SM 2015: Beslutsuppföljning

- ekonomiskt_styrdokument.tex
Raw unicode characters won't compile with pdflatex, which will cause this to fail on the server (https://styrdokument.datasektionen.se).
> Don't put paragraph characters in raw LaTeX files

- body.md
Texten var halvdan, så jag skrev om den. @Kahevajo
> Förbättra beskrivningen av styrdokumenten

- stadgar/body.md
Fixar lite diverse fel och byter ut alla trasiga referenser mot Markdown-länkar. Ska förstås inte förändra innebörden av något.
> Utför redaktionella ändringar på stadgarna

- reglemente/body.md
Fixar diverse fel, ska ej förändra någon innebörd.
> Utför redaktionella ändringar på reglementet

- reglemente/body.md
motioner som ändrade i styrdokumenten (reglementet) samt en redaktionell ändring.
Relevanta motioner: 9.1, 9.5, 9.7
> Revisions-SM 2016

- stadgar/body.md
fixat under 5.1.4.5.1 att presidiets urval ska ske enligt reglementets paragraf 3.12.6 inte 2.14.6 som det stod tidigare
> redaktionell ändring av läng

- reglemente/body.md
Snarare grammatik, men ändå. Redaktionell ändring.
> Grammatikfix

- dfunkpolicy/body.md
- ekonomiskt_styrdokument/body.md
- reglemente/body.md
> Glögg-SM 2016

- reglemente/body.md
Beslutsuppföljning av RevisionsSM ang datum för GlöggSM
> Beslutsuppföljning

- reglemente/body.md
- stadgar/body.md
Motion angående Otydlighet i Stadgarna
Motion angående Förtydligande och Ändrande av Valhandlingarna
Motion angående Sekretessbeläggning av Valhandlingarna
> Revisions-SM 2017 - diverse styrdokumentsändringar

- reglemente/body.md
Propp angående råden från Budget-SM.
> Beslutsuppföljning Revisions-SM 2017 (och lite Budget-SM 2016)

- reglemente/body.md
Reverts datasektionen/styrdokument#105
> Revert "Redaktionell ändring"

- reglemente/body.md
Allt ska man behöva göra själv.
> Rätt ska fan vara rätt.

- reglemente/body.md
Ersätter alla instanser av CSC med EECS
> Proposition angående CSC:s undergång (Revisions-SM 2018)

- stadgar/body.md
Proposition angående tolkning av stadgar
Extra-SM 2018
> Ändrade §1.6.2

- reglemente/body.md
Genomför ändringarna enligt 'Motionsvar angående gemensam internationell nämnd med media' som beslutades på Revisions-SM
> Uppdaterar §3.16 Internationella Nämnden

- reglemente/body.md
- stadgar/body.md
Beslutsuppföljning av stadgeändring som missades vid årsskiftet + Redaktionell ändring som var att ta bort ett en rad som var tillagd av misstag.
> Missad beslutsuppföljning Glögg-SM

- stadgar/body.md
Budget-SM 2018: Motion angående Omstrukturering av stadgarna
> Budget-SM 2018: Motion angående Omstrukturering av stadgarna

- reglemente/body.md
[Glögg-SM 2018 protokoll](https://dsekt-assets.s3.amazonaws.com/protokoll/glogg_sm_2018?AWSAccessKeyId=AKIAJZQSDTTOX6YRO37A&Signature=axSksqSXN6f21pQ4S1xx4KHLqck%3D&Expires=1579122067)
> Glögg-SM 2018: Motion angående d'Empire Strikes Back

- stadgar/body.md
rutiner kring ordförandebeslut
> Extra-SM Jan-19: Proposition angående rutiner kring ordförandebeslut

- reglemente/body.md
Make a change to §3.7.2 in Reglemente about the Organisation of Näringslivsgruppen according to a decision made during Glögg-SM 2018-11-29.
See minutes [here](https://static.datasektionen.se/protokoll/glogg_sm_2018).
> Change §3.7.2 in Reglemente

- alkoholpolicy/body.md
- reglemente/body.md
La till **§6 Alkohol i sektionslokalen** och justerade numrering i Alkoholpolicyn. 
Tog bort §8.1-8.6 under § Sektionslokalen och justerade numrering.
> Beslutsuppföljning Glögg-SM 2019: Motion angående Samboende är svårt

- reglemente/body.md
Beslut: Motion angående Informationsorganets och kommunikatörens roller.
Från Revisions-SM 2020-03-26.
> Beslutsuppföljning 20S01-02

- reglemente/body.md
Change accepted at the Audit-chapter meeting.
> Fixed changes according to the decision 20S01-12

- stadgar/body.md
commitmedelandet säger typ allt
> add statutes change from extra-SM January 2020

- reglemente/body.md
Edited 3.12.2, 3.12.4, 4.3.14, 4.3.14.1 and 4.3.14.2
> Beslutsuppföljning 20S02-19

- rekryteringspolicy/body.md
> Changes made in accordance with val-sm 2020

- dfunkpolicy/body.md
§1: ansvartsområde -> ansvarsområde
§1.2: efterträfare -> efterträdare
§1.2: rekomenderat -> rekommenderat
§1.5 annordnar -> anordnar
§1.7 Drektoratet -> D-rektoratet
§1.7 δ-funktionärna -> δ-funktionärerna
// Matteus Berg, Sekreterare 2020
> Redaktionella ändringar

- reglemente/body.md
Gjorde ändringen som röstades igenom med motionen "Ansiktslyft åt Ior".
> Ändrat under punkt 3.3.2

- reglemente/body.md
Proposition angående Verksamhetsplan 2021
> la till saker som tidigare fanns i VP enligt beslut på Glögg-SM

- reglemente/body.md
Ändrade punkten enligt motion angående Valberedningens roll.
> Ändrade punkt 3.12.4

- dfunkpolicy/body.md
Lade till 10.9 enligt propostion angångde verksamhetsplan i Dfunkpolicy.
Notera att den nya paragrafen §1.9 saknar rubrik. Det är mitt fel för jag specade ingen i proppen :upside_down_face:
> Beslutsuppföljning: 20S04-06

- reglemente/body.md
> Redaktionell ändring

- informationsspridningspolicy/body.md
> rimliga krav på infospridning, rev-SM 21

- alkoholpolicy/body.md
Genomförde ändringarna i beslutet för punkt 5.2: Proposition angående tydligare alkoholpolicy under Rev-SM 2021.
> 21S01-02: Proposition angående tydligare alkoholpolicy

- reglemente/body.md
> Uppdatera reglementet enligt propp om organ på KTH

- reglemente/body.md
Justerat baserat på ändringsyrkat för motionen "Uppstartandet av Datasladden"
> Justering för Rev-SM

- reglemente/body.md
> Fixat trasig markdown

- klimatpolicy/body.md
- klimatpolicy/meta.toml
- reglemente/body.md
Lägg till en klimatpolicy och lägg till i reglementet att vi har en klimatpolicy, enligt beslut på Val-SM 2021
Jag är inte så bra på att data så jag vet inte om detta är hur man lägger till flikar. Jag bara la till en mapp och la in samma filer som finns i de andra.
> 21s02-04 lägg till klimatpolicy

- stadgar/body.md
> Proposition angående revisionssed

- stadgar/body.md
> Proposition angående valprocess vid gemensam kandidatur

- reglemente/body.md
Uppdaterat paragraf 2 enl proposition angående informationshanteringspolicy
> Lagt till informationshanteringspolicyn

- reglemente/body.md
Scala och körmästare lades till i reglementet
> beslutsuppf motion 10 val-sm 210508

- stadgar/body.md
Ändrat punkt 2.5 enl propostion ang gästmedlemskap, samt omnumrerat punkten Medlemsavgift till 2.6
> Beslutsuppf glögg-SM 211207 gästmedlemskap

- informationsspridningspolicy/body.md
Uppdaterad informationsspridingspolicy, enligt prop 10 Budget-SM 2021
> Beslutuppf prop 6 Budget-SM 2021-11-09

- stadgar/body.md
> Fel i länkning till paragrafer

- stadgar/body.md
I ändringarna enl proppen för gästmedlemskap missades det att uppdatera punktlistan, vilket var del av proppen, så det ändras här.
> Lagt till gästmedlemskap i listan för medlemstyper

- README.md
- stadgar/body.md
Fortsättning på #192, detta var tydligen en grej upptäckte jag
> Fixa länkar del 2

- reglemente/body.md
> Big fat change adding Delad Verksamhet

- stadgar/body.md
Har ändrat punkt 3.16.6 enligt yrkandet på motionen angående urnval vid Extra-sm
> Beslutsuppf Extra-SM 2022-01-27 Urnval Extra-SM

- dfunkpolicy/body.md
Ändrar 1.5 i dfunkt-policyn så att den inkluderar JML-utbildningen utöver dfunk-utbildningen.
> 22S01-06 Beslutsuppf. jml-utbildning i dfunk-policy

- reglemente/body.md
Lägger till märkesreglering i reglement för prylmångleriet.
> 22S01-04 Beslutsuppf. markesreglering reglementet

- reglemente/body.md
GEEK heter endast GEEK i reglementet. 
Gör GEEK till en sluten nämnd. 
Tar bort hederdam ur reglementet.
> 22S01-03 Beslutsuppf. GEEK reglementet

- stadgar/body.md
Hittade några trasiga länkar i stadgarna, samt en lista som displayade trasigt, fixade dessa.
> Redaktionell ändring - fixa trasiga länkar och fixa en trasig lista i stadgarna

- informationshanteringspolicy/body.md
> Minor update

- reglemente/body.md
Change from `§5.3.10 > §4.3.10.1` to `§5.3.10 > §5.3.10.1`
> Editorial change of numbering

- stadgar/body.md
Ändra beslutsmässighet från 10 till 17.
> 22S02-01 beslutsmässighet

- reglemente/body.md
Geek byter namn till Ada i Reglementet.
Öfvermatrona byter namn till Adas ordförande.
> 22S02-10 Beslutsuppfl. Geek till Ada

- reglemente/body.md
i enl. med Originalmotionen för "reglementet för Geek", val-SM 2022
> uppdatera geek/ada i reglementet

- stadgar/body.md
Merge after https://github.com/datasektionen/styrdokument/pull/213
Innebär trots ändringsyrkanden (eller pga) en merge conflict med #214, behöver revisorstolkning
> Beslutsuppföljning 22Z02-04

- reglemente/body.md
Also did some redaktionella ändringar that was mentioned in the discussions leading up to the decision
Might have missed some though, so please check for more spelling/etc. that can be fixed.
> 22S03-18 Motion angående Slå ihop DEMON med Medias Musique Nämnd

- reglemente/body.md
Plockar bort Kingpin från reglementet. Observera att reglementet inte konsekvensnumreras.
> 22S04-8 Besluts uppflj yeeta Kingpin

- reglemente/body.md
Ändrar reglementet för att spegla att både JNO och SSO är skyddsombud.
> 22S04-18 Beslutsuppf. omformulering JNO och SSO-poster

- stadgar/body.md
Stadgeändring angående Förlängning av deadline för kallelse till SM.
> 22S04-4 Beslutsuppföljning Förlängning av deadline för kallelse till SM

- reglemente/body.md
Proposition angående införandet av talman
> 22S04-10 Beslutsuppföljning Proposition angående införandet av talman

- stadgar/body.md
> 22S04-5 - Lokallogistik i kallelser

- reglemente/body.md
> 22S04-22 - Reglementesändringar ny KF

- alkoholpolicy/body.md
- body.md
- dfunkpolicy/body.md
- dfunkpolicy/meta.toml
- ekonomiskt_styrdokument/body.md
- informationshanteringspolicy/body.md
- informationsspridningspolicy/body.md
- jamlikhetspolicy/body.md
- klimatpolicy/body.md
- reglemente/body.md
- rekryteringspolicy/body.md
- stadgar/body.md
closes #91 
Redaktionella ändringar, framför allt versalisering av titlar.
Fixade också konsekvent formatering av alla styrdokument. 
Markdown formatering av titlar med ========= och ----------- är katastrof.
> Editorial changes

- stadgar/body.md
> 23Z01-01 - Stadgeändringar ny KF

- reglemente/body.md
- stadgar/body.md
> 23Z01-06 - Renovera urnan

- reglemente/body.md
> 23S03-09 - Motion angående Startskott för VM

- reglemente/body.md
> fix typo reglemente

- reglemente/body.md
Nu numrerar jag om ett gäng punkter som ska strykas med annan propp, men jag numrerar hellre i onödan här än att missa någon sen
> 23S04-4 - julstädning av Reglementet

- uppförandepolicy/body.md
$ > §
Tydligen svårt med symboler...
> Fixa formateringsfel (redaktionell ändring)

- pm/pm_verksamhet/body.md
> 24D00-04 TECH-I-TAKA

- policies/klimatpolicy/body.md
- reglemente/body.md
Lägg till i styrdokumenten att D-SOL nu är ansvarig för miljö och hållbarhet. Proposition 2, punkt 8.2 på Rev-SM 2024.
> 24S01-00 Proposition angående D-SOLs hållbarhet

- stadgar/body.md
Update according to the decision, though with a terminating dot ;)
> 24-SM-01-M0 - Motion angående Stopp på snäva stopp

- reglemente/body.md
Radbrytet fuckade upp pga ett saknat enter, jag tror jag löste
> §3.12.4 Utlåtande fix

- pm/pm_stipendier/body.md
> 24D05-05 Ändring av PM för stipendier

- pm/pm_dfunk/body.md
> 24D05-04 Ändring av PM för dFunk

- pm/pm_verksamhet/body.md
- policies/uppforandepolicy/body.md
- reglemente/body.md
Attsats 6 har en liten redaktionell ändring.
> 24S03-12 Motion angående Jämlikhet 2.0: The Empire Strikes Back

- compose.yml
- ovrigt/body_sv.md
- pm/body_sv.md
- pm/pm_aterkommande/body_sv.md
- pm/pm_dfunk/body_sv.md
- pm/pm_informationshantering/body_sv.md
- pm/pm_verksamhet/body_sv.md
- policies/body_sv.md
- policies/jamlikhetspolicy/body_sv.md
- policies/rekryteringspolicy/body_sv.md
- policies/uppforandepolicy/body_sv.md
- reglemente/body_sv.md
- stadgar/body_sv.md
Started with the intention to just be some small formatting and typo fixes that I was annoyed at, but it grew a little in scope, partly due to list formatting.
Everything should be redaktionellt though.
Some of it might be opinionated (lists), so feedback is appreciated. I would like to reword some lists a bit more to make stuff more readable, but could possibly risk entering the territory of non-redaktionella changes then.
Oh, and I also added a `compose.yml` file for convenience when editing locally.
> Various fixes of varying sizes

- pm/pm_ekonomi/body_sv.md
- reglemente/body_sv.md
Proposition angående MKM som jag borde gjort för ett tag sedan. Några konsekvensnumreringar har smugit emellan men jag ändrar på ställena det borde ändrats på.
> 24S03-04: Proposition angående MKM

- reglemente/body_sv.md
Denna ska trädas i kraft 2025-01-01
> 24S03-05 Proposition angående införande av talmanspresidiet

- reglemente/body_sv.md
Reglementesändring.  Bifall på motionssvar. 
- Att i Reglementets 3.12.7 lägga till "“Kandidater som ställer upp i urnval får inte vara inblandade i administrationen av urnvalsprocessen.” enligt Motionssvar.
> 24S06-15 - Lägg locket på urnan

- pm/pm_alkohol/body_sv.md
- pm/pm_ekonomi/body_sv.md
Beslutades om på Ett Lurk-DM innan Glögg-SM
> 24D10-01 PM för ekonomi uppdatering

- reglemente/body_sv.md
- stadgar/body_sv.md
Ändringar på reglemente och stadgar från Motion angående Rimlig Revisionssed
> 25S02-14 - Motion angående Rimlig Revisionssed

- pm/pm_stipendier/body_sv.md
Add requested change in #329 which was missed.
Add correct heading level for §1.3
> Fix for #329

- pm/pm_alkohol/body_sv.md
Jag skurkade mig och gjorde båda att-satserna i en commit. Men de borde typ varit en att-sats ändå
> 25D03-04 - Ändringar i PM för Alkohol

- pm/pm_stipendier/body_sv.md
> 25D03-05 - Ändringar i PM för utmärkelser och stipendier

- pm/pm_alkohol/meta.toml
- pm/pm_ekonomi/meta.toml
- pm/pm_traditioner/meta.toml
Redaktionell ändring i namn för PM så att de är konsekventa med liten bokstav först.
> En ändring i namn för att det stör mig.

- pm/pm_aterkommande/body_sv.md
- policies/jamlikhetspolicy/body_sv.md
- policies/rekryteringspolicy/body_sv.md
- policies/samarbetspolicy/body_sv.md
- policies/uppforandepolicy/body_sv.md
> 25S03-02 - Pengarna STUDSar rakt in i sektionens konto

- policies/jamlikhetspolicy/body_sv.md
- policies/rekryteringspolicy/body_sv.md
- policies/samarbetspolicy/body_sv.md
- policies/uppforandepolicy/body_sv.md
Ingen ändring i klimatpolicy så ingen merge conflict hoppas jag
> 25S03-05 - Enhetliga policies

- reglemente/body_sv.md
Okej så den här gick igenom innan SM via DM men pga omständigheter blev den inte mergad in i master innan SM där skiten flyttades ut ur PM och in i reglementet. Alltihop är lite av en soppa men summa summarum här är ändringen.
> 25D04-01 - Ändring i PM för utmärkelser och stipendier

- pm/pm_ekonomi/body_sv.md
- reglemente/body_sv.md
att11s paragraf är redan struken. Det blev fel ordning på att18,19 men så är det. Att21 (05702d8075e92e11f4685b36e4ec132157cd5e06) tar med motionssvarets att1.
> 25S03-13 Motion angående Organ är det som någonsin hänt sektionen någonsin

- reglemente/body_sv.md
att3 och att9 ströks från MS. Paragrafer ur att11,12,17,23-28 existerar inte längre så görs ej (blev dock implementerade i #363).
> 25S03-11 Motion angående Reglementet patch 42.02.a

- pm/pm_partitioner/body_sv.md
> 25D07-08 - Skapande av partition
